respuesta = input("Estas aprendiendo a programar? 'Y' para si: ")
result = (respuesta == 'Y')
print("A ver, estas aprendiendo...")
print(result)
print("Invertimos el resultado usando NOT")
print(not(result))